complete -f -c comp -n '__fish_use_subcommand' -a 'gz' -d 'compress to gzip using pigz'
complete -f -c comp -n '__fish_use_subcommand' -a 'bz2' -d 'compress to bzip2 using lbzip2'
complete -f -c comp -n '__fish_use_subcommand' -a 'xz' -d 'compress to xz using pixz'
complete -f -c comp -n '__fish_use_subcommand' -a 'zst' -d 'compress to zst using pzstd'
complete -f -c comp -n '__fish_use_subcommand' -a 'tar.gz' -d 'create a tar archive and compress to gzip using pigz'
complete -f -c comp -n '__fish_use_subcommand' -a 'tar.bz2' -d 'create a tar archive and compress to bzip2 using lbzip2'
complete -f -c comp -n '__fish_use_subcommand' -a 'tar.xz' -d 'create a tar archive and compress to xz using pixz'
complete -f -c comp -n '__fish_use_subcommand' -a 'tar.zst' -d 'create a tar archive and compress to zst using pzstd'
complete -f -c comp -n '__fish_use_subcommand' -a 'zip' -d 'compress to zip using p7zip'
complete -f -c comp -n '__fish_use_subcommand' -a 'zip.crypt' -d 'compress to zip and encrypt ZipCrypt, using p7zip'
complete -f -c comp -n '__fish_use_subcommand' -a 'zip.aes' -d 'compress to zip and encrypt AES, using p7zip'
complete -f -c comp -n '__fish_use_subcommand' -a '7z' -d 'compress to 7z using p7zip'
complete -f -c comp -n '__fish_use_subcommand' -a '7z.aes' -d 'compress to 7z and encrypt AES, using p7zip'
