complete -f -c decomp -n '__fish_use_subcommand' -a '_' -d 'auto detection'
complete -f -c decomp -n '__fish_use_subcommand' -a 'gz' -d 'decompress from gzip using pigz'
complete -f -c decomp -n '__fish_use_subcommand' -a 'bz2' -d 'decompress from bzip2 using lbzip2'
complete -f -c decomp -n '__fish_use_subcommand' -a 'xz' -d 'decompress from xz using pixz'
complete -f -c decomp -n '__fish_use_subcommand' -a 'zst' -d 'decompress from zst using pzstd'
complete -f -c decomp -n '__fish_use_subcommand' -a 'tar.gz' -d 'decompress from gzip using pigz and extract from the tar archive'
complete -f -c decomp -n '__fish_use_subcommand' -a 'tar.bz2' -d 'decompress from bzip2 using lbzip2 and extract from the tar archive'
complete -f -c decomp -n '__fish_use_subcommand' -a 'tar.xz' -d 'decompress from xz using pixz and extract from the tar archive'
complete -f -c decomp -n '__fish_use_subcommand' -a 'tar.zst' -d 'decompress from zst using pzstd and extract from the tar archive'
complete -f -c decomp -n '__fish_use_subcommand' -a 'zip' -d 'decompress from zip using p7zip'
complete -f -c decomp -n '__fish_use_subcommand' -a '7z' -d 'decompress from 7zip using p7zip'
